import Head from 'next/head'

// export default function About() {
//     return (
//         <>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main>
//                 Hello About
//             </main>
//         </>
//     )
// }

import AppShell from '@/components/app-shell/app-shell';
import About from '@/components/pages/about';
// import Seo from '@/components/seo';
// import './css/about.css';


// markup
const AboutPage = () => {
  const seo = {
    title: 'About | KodeMonk | Yuvaraj V',
    description: 'Freelancer | Lead Software Engineer | Blogger | Linux Fan Boy',
    date: new Date(),
    path: '/about',
    image: '',
  };

  return (
    <AppShell>
      <About/>
    </AppShell>
  )
}

export default AboutPage
